
[desert]
parameters = [
    {weight=0.8, value=1},
    {weight=0.1, value=0}
]
layers = [
    {height=6, block="base:sand"},
    {height=-1, block="base:stone"},
    {height=1, block="base:bazalt"}
]
sea-layers = [
    {height=-1, block="base:water"}
]

[forest]
parameters = [
    {weight=0.7, value=0},
    {weight=0.5, value=0.2}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {below-sea-level=false, height=7, block="base:dirt"},
    {height=-1, block="base:stone"},
    {height=1, block="base:bazalt"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.4
plants = [
    {weight=1, block="base:grass"},
    {weight=0.03, block="base:flower"}
]
structure-chance = 0.032
structures = [
    {name="tree0", weight=1},
    {name="tree1", weight=1},
    {name="tree2", weight=1},
    {name="tower0", weight=0.002}
]

[taiga]
parameters = [
    {weight=0.1, value=0},
    {weight=0.8, value=0.3}
]
layers = [
    {below-sea-level=false, height=2, block="penrose:snow_block"},
    {below-sea-level=false, height=4, block="penrose:rooted_dirt"},
    {height=-1, block="base:stone"},
    {height=1, block="base:bazalt"}
]
sea-layers = [
    {height=1, block="penrose:ice"},
    {height=-1, block="base:water"}
]
plant-chance = 0.4
plants = [
    {weight=1, block="penrose:snow_grass"},
    {weight=0.5, block="penrose:snow"},
    {weight=0.03, block="penrose:withered_bush"}
]
structure-chance = 0.0112
structures = [
    {name="taiga_tree1", weight=1},
    {name="taiga_tree2", weight=1},
    {name="taiga_tree3", weight=1},
    {name="tower1", weight=0.0002},
]

[boulders_plains]
parameters = [
    {weight=0.6, value=0.5},
    {weight=0.6, value=0.2}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {below-sea-level=false, height=5, block="base:dirt"},
    {height=-1, block="base:stone"},
    {height=1, block="base:bazalt"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.3
plants = [
    {weight=1, block="base:grass"},
    {weight=0.03, block="base:flower"}
]
structure-chance=0.0002
structures = [
    {name="boulder0", weight=1},
    {name="boulder1", weight=1},
    {name="boulder2", weight=1}
]

[plains]
parameters = [
    {weight=0.6, value=0.5},
    {weight=0.6, value=0.0}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {below-sea-level=false, height=5, block="base:dirt"},
    {height=-1, block="base:stone"},
    {height=1, block="base:bazalt"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.3
plants = [
    {weight=1, block="base:grass"},
    {weight=0.03, block="base:flower"}
]
structure-chance=0.0005
structures = [
    {name="tree0", weight=1},
    {name="tree1", weight=1},
    {name="bone0", weight=0.05}
]

[bamboo_forest]
parameters = [
    {weight=0.5, value=1},
    {weight=0.5, value=0.5}
]
layers = [
    {below-sea-level=false, height=1, block="base:grass_block"},
    {below-sea-level=false, height=7, block="base:dirt"},
    {height=-1, block="base:stone"},
    {height=1, block="base:bazalt"}
]
sea-layers = [
    {height=-1, block="base:water"}
]
plant-chance = 0.4
plants = [
    {weight=1.2, block="penrose:fallen_sakura_flower"},
    {weight=1, block="base:grass"}
]
structure-chance = 0.072
structures = [
    {name="bamboo", weight=1},
    {name="sakura0", weight=0.01},
    {name="sakura1", weight=0.01},
    {name="sakura2", weight=0.01},
    {name="sakura3", weight=0.01},
]