tree0 = { }
tree1 = { }
tree2 = { }

taiga_tree0 = { }
taiga_tree1 = { }
taiga_tree2 = { }
taiga_tree3 = { }

teak_tree0 = { }
teak_tree1 = { }
teak_tree2 = { }

sakura0 = { }
sakura1 = { }
sakura2 = { }
sakura3 = { }

bush0 = { }

tower0 = { }
tower1 = { }

coal_ore0 = { }
iron_ore0 = { }

boulder0 = { }
boulder1 = { }
boulder2 = { }

bone0 = {lowering=4}

andesit_vein = { }
granit_vein = { }
diorit_vein = { }
tuff_vein = { }
gravel_vein = { }

bamboo = {lowering=-1}