tree0 = { }
tree1 = { }
tree2 = { }
tower0 = { }
tower1 = { }
taiga_tree0 = { }
coal_ore0 = { }
iron_ore0 = { }
taiga_house0 = { }
boulder0 = { }
boulder1 = { }
boulder2 = { }
bone0 = { }
andesit_vein = { }
granit_vein = { }
diorit_vein = { }
tuff_vein = { }
gravel_vein = { }
bamboo = { }